Repository bluecats-Perfect-Tower-2/bluecats-PerfectTower2-comp., pull requests merged in 2023-09, with the labels that each got.

#11 Update README.md
  Challenges/Hardmode/Pre Era/README.md
Labels: help wanted, good first issue, Change

#20 Changed c2-4 for even faster completion
  Challenges/Hardmode/Pre Era/README.md
Labels: Change

#21 Added solutions for c8-2 and c8-3
  Challenges/Hardmode/Pre Era/README.md
Labels: New Challenge

#22 Added solutions for c8-1 and c8-4
  Challenges/Hardmode/Pre Era/README.md
Labels: New Challenge

#23 Changed c6-3 and c6-5
  Challenges/Hardmode/Pre Era/README.md
Labels: Change

#24 Changed c8-3
  Challenges/Hardmode/Pre Era/README.md
Labels: Change

#25 Improve c8-3 & 8-4 (as well as c6-6 AI)
  Challenges/Hardmode/Pre Era/README.md
Labels: Change
